# Default values for codeserver.
# This is a YAML-formatted file.
replicaCount: 1

image:
  repository: cdfng/codeserver
  pullPolicy: IfNotPresent
  tag: "4"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   runAsNonRoot: true
   runAsUser: 1000

service:
  type: LoadBalancer
  port: 80

resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
 - name: kubevolume
   secret:
     secretName: codeserver_secret
     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
 - name: kubevolume
   mountPath: "/etc/codeserver"
   readOnly: true